### ISSUE TITLE
struktura talii i fiszki

### ISSUE THREAD

**Issue by jligeza** [blstream/StudyBox_Backend#1]
Chciałbym się dowiedzieć jak będzie wyglądać jsonowa struktura talii i fiszki. Potrzebuję tych informacji do zrobienia tymczasowej atrapy back endu.

**Comment by VanDavv** [comment]
Mock backendu będzie w czwartek prawdopodobnie gotowy

**Comment by mlotysz** [comment]
Nie jestem pewny. We czwartek może dostaniemy wsad od grupy Analizy i to co przygotowaliśmy zostanie zmienione. Jednak URLe wskazane w naszej dokumentacji raczej się nie zmienią: http://docs.studybox.apiary.io/#
